name: Debug build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/debug.yml'
  pull_request:
    branches:
      - main
      
env:
  UPLOAD_RELEASE: true

jobs:
  build:
    name: Debug build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Build
        run: |
          ./init.sh
          ./build.sh
	  - name: FindPath
        run: |
          AAR=$(find . -name '*.aar')
          echo "AAR=$AAR"
      - uses: actions/upload-artifact@v2
        with:
          name: libcore.aar
          path: ./libcore.aar